version: '3.8'

services:
  nginx:
    image: nginx:alpine
    container_name: audible-luxe-nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - backend
    networks:
      - audible-luxe

  frontend:
    image: zenjabba/audible-luxe-frontend:latest
    container_name: audible-luxe-frontend
    restart: unless-stopped
    environment:
      NODE_ENV: production
      NEXT_PUBLIC_API_URL: /api
    depends_on:
      - backend
    networks:
      - audible-luxe

  backend:
    image: zenjabba/audible-luxe-backend:latest
    container_name: audible-luxe-backend
    restart: unless-stopped
    environment:
      NODE_ENV: production
      DATABASE_URL: file:/app/data/production.db
      REDIS_HOST: redis
      REDIS_PORT: 6379
      V3_API_BASE_URL: ${V3_API_BASE_URL}
      V3_API_LICENSE_KEY: ${V3_API_LICENSE_KEY}
      SESSION_SECRET: ${SESSION_SECRET}
      PORT: 8080
      LOG_LEVEL: ${LOG_LEVEL:-info}
      CORS_ORIGIN: http://frontend:3000
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    depends_on:
      - redis
    networks:
      - audible-luxe

  redis:
    image: redis:7-alpine
    container_name: audible-luxe-redis
    restart: unless-stopped
    command: redis-server --appendonly yes --maxmemory 256mb --maxmemory-policy allkeys-lru
    volumes:
      - redis-data:/data
    networks:
      - audible-luxe

volumes:
  redis-data:
    driver: local

networks:
  audible-luxe:
    driver: bridge